# Generated by Django 4.2.27 on 2026-01-15 23:34

import captionapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to=captionapp.models.user_video_path)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube Shorts')], default='instagram', max_length=20)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('funny', 'Funny'), ('inspirational', 'Inspirational'), ('casual', 'Casual'), ('educational', 'Educational'), ('dramatic', 'Dramatic')], default='friendly', max_length=20)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('detected_objects', models.JSONField(blank=True, default=list, null=True)),
                ('audio_transcript', models.TextField(blank=True)),
                ('video_description', models.TextField(blank=True)),
                ('generated_caption', models.TextField(blank=True)),
                ('suggested_hashtags', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_text', models.TextField()),
                ('platform', models.CharField(max_length=20)),
                ('tone', models.CharField(max_length=20)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='captionapp.videoupload')),
            ],
            options={
                'verbose_name_plural': 'Caption Histories',
                'ordering': ['-used_at'],
            },
        ),
    ]
